### ISSUE TITLE
Mods can't use /me

### ISSUE THREAD

**Issue by Twentydragon** [PiLoT-/pcgamer-minecraft-server-usa#38]
For some reason, moderators can't use the "/me" command.

Instead, we get the error "You don't have permission to speak in Global."

**Comment by PiLoT-** [comment]
ill have to check, but /me gave a vulnerability so i had to disable it server wide

**Comment by Twentydragon** [comment]
Admins can still use it.

**Comment by PiLoT-** [comment]
Fixed
