### ISSUE TITLE
Kick messages don't display

### ISSUE THREAD

**Issue by Twentydragon** [PiLoT-/pcgamer-minecraft-server-usa#40]
When a user is kicked, we used to see the message declaring that they've been kicked and the reason provided. This appears not to be the case anymore. Even staff can't see the messages.

Steps to reproduce:
1. Have any other staffer kick a user.
2. Watch for the kick notice.

**Comment by PiLoT-** [comment]
This is on the to do list. Has been for a few months lol

**Comment by Twentydragon** [comment]
Figured I'd formalize it by making a thread for it, especially since I've only started observing this recently (within the last couple weeks).

**Comment by QueueAmI** [comment]
When I looked into this, I had some trouble figuring out the code. The
programmer changed the way it worked and made it really hard to fix.
